version: 1.2
workflows:
- name: main
  subclass: Galaxy
  publish: true
  primaryDescriptorPath: /pox-virus-half-genome.ga
  authors:
  - name: Viktoria Isabel Schwarz
    identifier: https://orcid.org/0000-0001-6897-1215
  - name: Wolfgang Maier
    identifier: https://orcid.org/0000-0002-9464-6640
