version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /VGP-Decontamination-pipeline---Db-not-included.ga
  subclass: Galaxy
  testParameterFiles:
  - /VGP-Decontamination-pipeline---Db-not-included-tests.yml
