version: 1.2
workflows:
- name: main
  primaryDescriptorPath: /hic_tabix_to_cool_cooler.ga
  subclass: Galaxy
- name: main
  primaryDescriptorPath: /Hi-C_fastqToPairs_hicup.ga
  subclass: Galaxy
- name: main
  primaryDescriptorPath: /chic_fastq_to_cool_hicup_cooler.ga
  subclass: Galaxy
- name: main
  primaryDescriptorPath: /hic_fastq_to_cool_hicup_cooler.ga
  subclass: Galaxy
- name: main
  primaryDescriptorPath: /hic_fastq_to_pairs_hicup.ga
  subclass: Galaxy
  testParameterFiles:
  - /hic_fastq_to_pairs_hicup-tests.yml
